use_frameworks!

platform :ios, '8.0'

target 'CQRequest_Example' do
  pod 'CQRequest', :path => '../'
  pod 'MJExtension', '~> 3.0.13'
  target 'CQRequest_Tests' do
    inherit! :search_paths

    
  end
end
